# Generated by Django 4.1.3 on 2022-12-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formula1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormulaDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pos", models.IntegerField(blank=True, null=True)),
                ("team", models.CharField(max_length=50)),
                ("pts", models.IntegerField(blank=True, null=True)),
                ("year", models.CharField(blank=True, max_length=100, null=True)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(name="TODO",),
    ]
