# Generated by Django 4.1.3 on 2022-12-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formula1", "0002_formuladetail_delete_todo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formuladetail",
            name="team",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
